In [2]:
import numpy as np

Q1.Data science problems on reading, concatenating, Data manipulation, and saving Data.

In the Data Science project, for analyzing climate data to predict corp yield from various stations, climate data are captured from ten various stations ie.climate_data_station1.csv to climate_data_station10.csv
File url_link=https://github.com/svkarthik86/Advanced-python/tree/main/climate_project
n 
as Data analytics you have to read all files generated from stations and concatenate all files into one single data.
and then calculate corp yield.

for calculating the corp yield as a weighted sum of the temperature, rainfall, and humidity
yield_of_corp  = w1 * temperature + w2 * rainfall + w3 * humidity
w1, w2, w3 = 0.3, 0.2, 0.5

using the above information to generate yield_of_corp data and then concatenate yield_of_corp as the last column in climate_data.
finally, save the result to climate_result.csv

In [3]:
file1=np.genfromtxt('climate_data_station1.csv',delimiter=',',dtype=int)
file1

array([[ 25,  76,  99],
       [ 39,  65,  70],
       [ 59,  45,  77],
       ...,
       [ 95, 100,  66],
       [ 75,  97,  24],
       [ 87,  59,  81]])

In [28]:
for i in range(1,11):
    print(i)
    file=f"climate{i}"
    data=np.genfromtxt(file,delimiter=',')
    con=np.concatenate((data),axis=0)
    print(con)
con

1


PermissionError: [Errno 13] Permission denied: 'climate'

In [17]:
con.reshape(1500,2)

array([[85., 51.],
       [88., 47.],
       [66., 95.],
       ...,
       [70., 71.],
       [91., 92.],
       [39., 76.]])

In [21]:
con.shape

(3000,)

In [13]:
import numpy as np
import os
os.listdir()
k=np.array([])
for i in os.listdir():
    if i.startswith('climate_data_station'):
        a=np.genfromtxt(i,delimiter=',',skip_header=True)
        if k.size == 0:
            k = a
        else:
            k=np.concatenate((k,a),axis=0)
k

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [47., 91., 86.],
       [90., 99., 96.],
       [40., 46., 78.]])

In [11]:
k=np.array([])
a=np.concatenate([np.genfromtxt(f'climate_data_station{i}.csv',delimiter=',',skip_header=True)for i in range(1,11)])
a

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [15]:
w1,w2,w3=0.3,0.2,0.5
result=[]
yield_of_corp=w1*b[:,0]+w2*b[:,1]+w3*b[:,2]
data=np.column_stack((b,yield_of_corp))
result.append(data)
result=np.concatenate(result,axis=0)
np.savetext('final_result.csv',result,delimiter=',',fmt='%0.1f')

NameError: name 'b' is not defined